name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install pnpm from package.json `packageManager`
      - uses: pnpm/action-setup@v4
        with:
          # DO NOT set "version"
          run_install: false

      # 2) Node + pnpm cache (pnpm now exists)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # 3) Install deps
      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
